-- 将该建表 SQL 语句，添加到 yudao-module-ai-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "ai_model" (
                                          "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                          "name" varchar NOT NULL,
                                          "api_key" varchar,
                                          "model_name" varchar NOT NULL,
                                          "model_type" int NOT NULL,
                                          "remark" varchar,
                                          "creator" varchar DEFAULT '',
                                          "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                          "updater" varchar DEFAULT '',
                                          "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                          "deleted" bit NOT NULL DEFAULT FALSE,
                                          "tenant_id" bigint NOT NULL,
                                          PRIMARY KEY ("id")
    ) COMMENT 'AI模型表';
